### ISSUE TITLE
node doesn't know about ES6 features

### ISSUE THREAD

**Issue by dKab** [domenic/count-to-6#19]
I tried to run this line in my terminal: 
node -e 'function test(...args) { console.log(args.join(' ')) } test('this' 'is' 'a' 'test');'
and I got SyntaxError: Unexpected token .
My node version is 0.10.35 , but apparently it doesn't recognize REST feature syntax (the "...args" part) and I'm curious why is that? Given the fact that when I use this syntax to solve count-to-6 workshop tasks it works alright and it runs in the same environment, right? I mean when I run 'count-to-6 verify file.js' it uses nodejs installed on my machine to evaluate the script. Am i missing something here?

**Comment by domenic** [comment]
> I mean when I run 'count-to-6 verify file.js' it uses nodejs installed on my machine to evaluate the script. 

Not quite! As we say in the readme,

> It leverages the excellent Traceur compiler to allow you to write code with ES6 syntax, today.

That is, before running any Node code, we compile it with Traceur.

You should be able to get a similar experience if you use my [Traceur Runner](https://github.com/domenic/traceur-runner) project. `npm install -g traceur-runner`, then do `traceur-runner myscript.js`.
