### ISSUE TITLE
Update to workshopper 2.x/workshopper-exercise 2.x

### ISSUE THREAD

**Issue by domenic** [domenic/count-to-6#22]
Just updating in package.json causes failures; it seems like the Traceur processor is no longer working.

Here's all the places we create custom plugin-ey things:

- https://github.com/domenic/count-to-6/blob/master/lib/setup-basics.js
- https://github.com/domenic/count-to-6/blob/master/lib/single-function-processor.js
- https://github.com/domenic/count-to-6/blob/master/lib/traceur-processor.js

Plus the initial setup, which might need a tiny bit of updating: https://github.com/domenic/count-to-6/blob/master/lib/count-to-6.js

Here is a sample exercise:

https://github.com/domenic/count-to-6/blob/master/lib/exercises/tagged_template_strings/exercise.js

Anyone familiar with recent workshoppers want to help out with a pull request?

**Comment by domenic** [comment]
@rvagg any chance you could give me a quick rundown on what changed in workshopper that might impact me?

**Comment by domenic** [comment]
Nevermind, the Traceur processor was failing for unrelated reasons. All upgraded, sorry for bothering you @rvagg.

**Comment by rvagg** [comment]
phew, I was concerned about having to get into the workshopper headspace, which is a bit of an effort at this stage!
