### ISSUE TITLE
Extra Escape Character Rendered in Problem "Template Strings"

### ISSUE THREAD

**Issue by evelynStraigt** [domenic/count-to-6#33]
Hey!  I'm one of a group of mentors running NodeSchool events in NYC.  We've mentored your workshop at our events a few times and we love it!

Today we had some attendees point out that the explanation of the initial template strings problem was misleading.  They had gotten confused and thought there was a need to escape the initial backtick due to the way the explanation rendered.

Image :  https://s3.amazonaws.com/uploads.hipchat.com/22279/1042749/nBHBM5ItyiFMmyp/IMG_20160225_195901.jpg

Should be a really fast, easy fix - I'm doing this from my phone now but I'd be glad to take a look and help fix it this weekend if you're not going to beat me to it before then.   (=

**Comment by evelynStraigt** [comment]
Sorry for huge image.   O=

**Comment by domenic** [comment]
Oh, hmm, OK, I wonder if the markdown processing for nodeschool has changed since I first did this. Pull requests appreciated!
