### ISSUE TITLE
how do I move forward with the lesson or show solution?

### ISSUE THREAD

**Issue by gideondsouza** [domenic/count-to-6#41]
So if I'm stuck at a challenge isn't there an option to just show me the solution? IIRC some of the other lessons has this.

The reason problem is I'm stuck on one of the lesson. I don't remember the details, I will put them up here.

**Comment by zbicin** [comment]
[You can always look up the solutions in the source code](https://github.com/domenic/count-to-6/tree/master/lib/exercises), but hey, don't tell this to anybody, alright? ;)
