### ISSUE TITLE
DeprecationWarning?

### ISSUE THREAD

**Issue by jenstrickland** [domenic/count-to-6#44]
I'm doing the count-to-6 workshop and keep getting the error: "(node:20733) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead"

**Comment by zbicin** [comment]
Hi @jenstrickland, thanks for pointing this out. :)

It looks like a minor issue now, but I'll have a closer look at it in a spare minute.
