### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by sevku** [domenic/count-to-6#46]
Can't start it. It shows a Reference Error: count is not defined when I enter count-to-6 in node

**Comment by zbicin** [comment]
I'm not sure what do you mean by 

> when I enter count-to-6 in node

Have you installed the package globally from your terminal (mind the `-g` switch)
```
npm install -g count-to-6
``` 
and then ran it using
```
count-to-6
````
?

**Comment by sevku** [comment]
Basically the second command doesn't work. Sorry as you could probably guess, I'm a complete noob. But I can install it but not run it.

**Comment by sevku** [comment]
It's alright. I typed it directly into node. Sorry.

**Comment by zbicin** [comment]
No worries, happens to everyone. ;)
